# Generated by Django 3.2.5 on 2021-08-22 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocation_name', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Frequency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency_name', models.CharField(max_length=30)),
                ('months', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='InterestMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest_method_name', models.CharField(max_length=30)),
                ('month_counting', models.CharField(max_length=30)),
                ('year_counting', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_name', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoanBalanceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoanCalc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField()),
                ('loan_amt', models.FloatField()),
                ('rewritten_int', models.FloatField()),
                ('loan_date', models.DateField()),
                ('first_pmt_date', models.DateField()),
                ('nbr_of_pmts', models.IntegerField()),
                ('int_rate', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.allocation')),
                ('int_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.interestmethod')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.loan')),
                ('pmt_frequency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.frequency')),
            ],
        ),
        migrations.CreateModel(
            name='LoanSched',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pmt_nbr', models.CharField(blank=True, max_length=4, null=True)),
                ('pmt_date', models.DateField()),
                ('payment', models.FloatField()),
                ('begin_prin', models.FloatField()),
                ('add_prin', models.FloatField()),
                ('prin_pmt', models.FloatField()),
                ('end_prin', models.FloatField()),
                ('begin_int', models.FloatField()),
                ('add_int', models.FloatField()),
                ('int_pmt', models.FloatField()),
                ('end_int', models.FloatField()),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.loan')),
                ('loan_calc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.loancalc')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentVariationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RollTxnType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RollTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txn_year', models.IntegerField(blank=True)),
                ('txn_month', models.IntegerField(blank=True)),
                ('amount', models.FloatField()),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.loan')),
                ('loan_balance_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.loanbalancetype')),
                ('loansched', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.loansched')),
                ('roll_txn_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.rolltxntype')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pmt_nbr_from', models.IntegerField()),
                ('pmt_nbr_to', models.IntegerField()),
                ('variation_value', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loan_calc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.loancalc')),
                ('variation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.paymentvariationtype')),
            ],
        ),
        migrations.CreateModel(
            name='LoanRoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_year', models.IntegerField(blank=True)),
                ('roll_month', models.IntegerField(blank=True)),
                ('begin', models.FloatField()),
                ('add', models.FloatField()),
                ('reduce', models.FloatField()),
                ('end', models.FloatField()),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.loan')),
                ('loan_balance_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.loanbalancetype')),
            ],
        ),
        migrations.CreateModel(
            name='CalcSched',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pmt_nbr', models.IntegerField()),
                ('pmt_date', models.DateField()),
                ('payment', models.FloatField()),
                ('begin_prin', models.FloatField()),
                ('add_prin', models.FloatField()),
                ('prin_pmt', models.FloatField()),
                ('end_prin', models.FloatField()),
                ('begin_int', models.FloatField()),
                ('add_int', models.FloatField()),
                ('int_pmt', models.FloatField()),
                ('end_int', models.FloatField()),
                ('loan_calc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.loancalc')),
            ],
        ),
    ]
